@server = http://localhost:4004

###
GET {{server}}/odata/v4/pc-stsrv/$metadata
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/Test
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/OrgUnit
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/OrgUnitGroup
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/Department
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/FoJob
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/HRPersonnelArea
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/CustEmployeeGroup
Content-Type: application/json


###
GET {{server}}/odata/v4/pc-stsrv/TestRules
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_EligibilityRules
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_EligibilityRules?$filter=cust_ECField eq 'empStatus'
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_EligibilityRules?$filter=cust_ECField eq 'empGroup'
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_EligibilityRules?$filter=cust_ECField eq 'empSubGroup'
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_EligibilityRules?$filter=cust_ECField eq 'compTransp'
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_EligibilityRules?$filter=cust_EligibilityType eq 'children'
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_EligibilityRules?$filter=cust_ECField eq 'empStatus' and cust_EligibilityType eq 'employee' and effectiveStartDate le '2025-01-01' and mdfSystemRecordStatus eq 'N'
Content-Type: application/json

###
GET {{server}}/odata/v4/pc-stsrv/ST_DependentsDetails?$filter=cust_Dependents_mdfSystemTransactionSequence eq '2'
Content-Type: application/json


###
GET {{server}}/odata/v4/pc-stsrv/ST_EmpPayCompRecurring
Content-Type: application/json